// <auto-generated />
namespace GoTAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class returnIcollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(returnIcollection));
        
        string IMigrationMetadata.Id
        {
            get { return "202003062333425_returnIcollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
