namespace GoTAPI.Data.Migrations
{
    using GoTAPI.Data.DataClasses;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<GoTAPI.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(GoTAPI.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.

            context.Houses.AddOrUpdate(
                h => h.Name,
                new House { Name = "Stark", Sigil = "A grey direwolf on a white field", Words = "Winter Is Coming", Region = "The North" },
                new House { Name = "Lannister", Sigil = "A golden lion rampant on a crimson field", Words = "Hear Me Roar", Region = "The Westerlands" },
                new House { Name = "Targaryen", Sigil = "A red three-headed dragon, on a black field", Words = "Fire and Blood", Region = "The Crownlands" },
                new House { Name = "Baratheon", Sigil = "A crowned black stag salient on a gold field", Words = "Ours Is the Fury", Region = "The Stormlands" },
                new House { Name = "Baratheon of King's Landing", Sigil = "The crowned stag of Baratheon black on gold and the lion of Lannister golden on red", Words = "Ours Is the Fury", Region = "The Crownlands" },
                new House { Name = "Baratheon of Dragonstone", Sigil = "The crowned black stag of Baratheon enclosed within the fiery red heart of the Lord of the Light", Words = "Ours is the Fury", Region = "The Stormlands" },
                new House { Name = "Tyrell", Sigil = "A golden rose on a green field", Words = "Growing Strong", Region = "The Reach" },
                new House { Name = "Martell", Sigil = "A red sun pierced by a gold spear, on an orange field", Words = "Unbowed, Unbent, Unbroken", Region = "Dome" },
                new House { Name = "Tully", Sigil = "A silver trout leaping on a red and blue background", Words = "Family, Duty, Honor", Region = "The Riverlands" },
                new House { Name = "Arryn", Sigil = "A white falcon volant and crescent moon on a blue field", Words = "As High as Honor", Region = "The Vale of Arryn" },
                new House { Name = "Greyjoy", Sigil = "A golden kraken on a black field", Words = "We Do Not Sow", Region = "Iron Islands" },
                new House { Name = "Frey", Sigil = "The two stone grey towers and bridge of the Twins, on a dark grey field, surmounting an escutcheon of blue water", Words = "We Stand Together", Region = "The Riverlands" },
                new House { Name = "Bolton", Sigil = "A red flayed man, hanging upside-down on a white X-shaped cross, on a black background", Words = "Our Blades Are Sharp", Region = "The North" },
                new House { Name = "Florent", Sigil = "A red gold fox on ermine", Words = "Unknown", Region = "The Reach" },
                new House { Name = "Redwyne", Sigil = "A burgundy grape cluster on a white field", Words = "Ripe for Victory", Region = "The Reach" },
                new House { Name = "Umber", Sigil = "Four silver chains linked by a central ring on dark red", Words = "Unknown", Region = "The North" },
                new House { Name = "Mormont", Sigil = "A rampant (formerly passant) black bear on a white field, surrounded by a green escutcheon", Words = "Here We Stand", Region = "The North" },
                new House { Name = "Tarly", Sigil = "A striding huntsman, red on green", Words = "First In Battle", Region = "The Reach" },
                new House { Name = "Karstark", Sigil = "A white sunburst on black", Words = "The Sun of Winter", Region = "The North" },
                new House { Name = "Payne", Sigil = "Purple and white chequy with goid coins in the checks.", Words = "Unknown", Region = "The Westerlands" },
                new House { Name = "Reed", Sigil = "a black lizard-lion on a grey-green field", Words = "Unknown", Region = "The North" },
                new House { Name = "Royce", Sigil = "A shower of pebbles on an orange field surrounded by runes", Words = "We Remember", Region = "The Vale of Arryn" },
                new House { Name = "Dondarrion", Sigil = "A forked purple lightning bolt on a black starry sky", Words = "Unknown", Region = "The Stormlands" },
                new House { Name = "Tollett", Sigil = "Pily grey and black", Words = "When All Is Darkest", Region = "The Vale of Arryn" },
                new House { Name = "Glover", Sigil = "An armored silver fist on a scarlet field", Words = "Unknown", Region = "The North" },
                new House { Name = "Blount", Sigil = "A red bend sinister between two black porcupines on green", Words = "Unknown", Region = "The Crownlands" },
                new House { Name = "Brune", Sigil = "A bear paw, brown or white, within a tressure brown", Words = "Unknown", Region = "The Crownlands" },
                new House { Name = "Tarth", Sigil = "Yellow suns on rose quartered with white crescents on azure", Words = "Unknown", Region = "The Stormlands" },
                new House { Name = "Clegane", Sigil = "Three dogs on a yellow field", Words = "Disregard Monarchs, Acquire Poultry", Region = "The Westerlands" },
                new House { Name = "Seaworth", Sigil = "A black ship on a pale grey field, with a white onion on its sails", Words = "Whether High or Low", Region = "The Stormlands" },
                new House { Name = "Baelish", Sigil = "A grey stone head with fiery eyes, on a light green field", Words = "Chaos is a Ladder", Region = "The Vale of Arryn" },
                new House { Name = "Bronn", Sigil = "A flaming arrow bendwise", Words = "Unknown", Region = "The Reach" },
                new House { Name = "Selmy", Sigil = "Three stalks of yellow wheat on a brown field", Words = "Unknown", Region = "The Stormlands" },
                new House { Name = "Thorne", Sigil = "Gules, a flail argent within a bord", Words = "Unknown", Region = "The Crownlands" },
                new House { Name = "Trant", Sigil = "A black hanged man on a blue field", Words = "So End Our Foes", Region = "The Stormlands" },
                new House { Name = "Slynt", Sigil = "A bloody spear, gold on black, with a border of checkered gold and black", Words = "Unknown", Region = "The Crownlands" },
                new House { Name = "Yarwyck", Sigil = "Two bronze halberds crossed between four red diamonds on a white field", Words = "Unknown", Region = "The Westerlands" },
                new House { Name = "Marsh", Sigil = "Ten frogs, 4-3-2-1, green on a yellow field", Words = "Unknown", Region = "The North" },
                new House { Name = "Hollard", Sigil = "Barry red and pink, three golden crowns on a blue (or black) chief", Words = "Unknown", Region = "The Crownlands" },
                new House { Name = "Cassel", Sigil = "Ten white wolves' heads, 4-3-2-1, on grey with a black border", Words = "Unknown", Region = "The North" },
                new House { Name = "Lorch", Sigil = "A black manticore on a white field, beneath a crimson chief with three gold coins", Words = "Unknown", Region = "The Westerlands" },
                new House { Name = "Waynwood", Sigil = "A broken black wheel, on a green field", Words = "Unknown", Region = "The Vale of Arryn" },
                new House { Name = "Wode", Sigil = "Three white hedgehogs, on a yellow field", Words = "Touch Me Not", Region = "The Riverlands" },
                new House { Name = "Lefford", Sigil = "A golden inverted pile on a sky-blue field, a yellow sun in the first", Words = "Unknown", Region = "The Westerlands" },
                new House { Name = "Moore", Sigil = "Three bronze spearheads, on a white field, within a bronze embattled border", Words = "Unknown", Region = "The Vale of Arryn" },
                new House { Name = "Kenning", Sigil = "The storm god's cloudly hand, pale grey, yellow lightning flashing from the fingertips, on black", Words = "Unknown", Region = "Iron Islands" },
                new House { Name = "Rykker", Sigil = "Two black warhammers crossed on a white saltire on blue", Words = "Unknown", Region = "The Crownlands" },
                new House { Name = "Manderly", Sigil = "A white merman with dark green hair, beard and tail, carrying a black trident, over a blue-green field", Words = "Unknown", Region = "The North" },
                new House { Name = "Humble", Sigil = "Unknown", Words = "Unknown", Region = "Iron Islands" },
                new House { Name = "Corbray", Sigil = "Three black ravens in flight, holding three red hearts, on a white field", Words = "Unknown", Region = "The Vale of Arryn" },
                new House { Name = "Blackmont", Sigil = "A black vulture with a pink infant in its claws, on yellow", Words = "Unknown", Region = "Dorne" },
                new House { Name = "Hunter", Sigil = "Five silver arrows, fanned, on brown", Words = "Unknown", Region = "The Vale of Arryn" },
                new House { Name = "Stokeworth", Sigil = "A white lamb holding a golden goblet on a green field", Words = "Proud To Be Faithful", Region = "The Crownlands" },
                new House { Name = "Dayne", Sigil = "A white sword and falling star crossed on lilac", Words = "Unknown", Region = "Dorne" },
                new House { Name = "Hightower", Sigil = "A white tower crowned with flames on smoke grey", Words = "We Light the Way", Region = "The Reach" },
                new House { Name = "Mallister", Sigil = "A silver eagle, displayed, on an indigo field", Words = "Above the Rest", Region = "The Riverlands" },
                new House { Name = "Bracken", Sigil = "A red stallion upon a gold shield, on a brown field", Words = "Unknown", Region = "The Riverlands" },
                new House { Name = "Crakehall", Sigil = "A brindled black and white boar on a brown field", Words = "None so Fierce", Region = "The Westerlands" },
                new House { Name = "Hetherspoon", Sigil = "An oak spoon within a white cartouche, on a field of orange and black diamonds", Words = "Unknown", Region = "The Westerlands" },
                new House { Name = "Marbrand", Sigil = "An orange burning tree, on a smoky field", Words = "Burning Bright", Region = "The Westerlands" },
                new House { Name = "Poole", Sigil = "A blue plate on white, with a grey tressure", Words = "Unknown", Region = "The North" },
                new House { Name = "None", Sigil = "", Words = "", Region = "" });
            context.SaveChanges();
            context.Characters.AddOrUpdate(
                 c => c.Name,
                 new Character { HouseId = 2, Name = "Tyrion Lannister", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Peter Dinklage", CauseOfDeath = "N/A" },
                 new Character { HouseId = 2, Name = "Cersei Lannister", Alive = false, EpisodeOfDeath = 72, Gender = "Female", Actor = "Lena Headey", CauseOfDeath = "Crushed by rubble" },
                 new Character { HouseId = 3, Name = "Daenerys Targaryen", Alive = false, EpisodeOfDeath = 73, Gender = "Female", Actor = "Emilia Clarke", CauseOfDeath = "Stabbed by Jon Snow" },
                 new Character { HouseId = 1, Name = "Jon Snow", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Kit Harington", CauseOfDeath = "N/A" },
                 new Character { HouseId = 1, Name = "Sansa Stark", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Sophie Turner", CauseOfDeath = "N/A" },
                 new Character { HouseId = 1, Name = "Arya Stark", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Maisie Williams", CauseOfDeath = "N/A" },
                 new Character { HouseId = 2, Name = "Jaime Lannister", Alive = false, EpisodeOfDeath = 72, Gender = "Male", Actor = "Nikolaj Coster-Waldau", CauseOfDeath = "Crushed by rubble" },
                 new Character { HouseId = 17, Name = "Jorah Mormont", Alive = false, EpisodeOfDeath = 70, Gender = "Male", Actor = "Iain Glen", CauseOfDeath = "Killed by Wights protecting Daenerys" },
                new Character { HouseId = 18, Name = "Samwell Tarly", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "John Bradley", CauseOfDeath = "N/A" },
                new Character { HouseId = 11, Name = "Theon Greyjoy", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Alfie Allen", CauseOfDeath = "Stabbed with own spear by the Night King" },
                new Character { HouseId = 62, Name = "Lord Varys", Alive = false, EpisodeOfDeath = 72, Gender = "Male", Actor = "Conleth Hill", CauseOfDeath = "Burned to death by dragon fire on Daenerys' orders" },
                new Character { HouseId = 30, Name = "Davos Seaworth", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Liam Cunningham", CauseOfDeath = "N/A" },
                new Character { HouseId = 28, Name = "Brienne of Tarth", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Gwendoline Christie", CauseOfDeath = "N/A" },
                new Character { HouseId = 31, Name = "Petyr 'Littlefinger' Baelish", Alive = false, EpisodeOfDeath = 67, Gender = "Male", Actor = "Aidan Gillen", CauseOfDeath = "Throat slit by Arya Stark" },
                new Character { HouseId = 1, Name = "Bran Stark", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Isaac Hempstead Wright", CauseOfDeath = "N/A" },
                new Character { HouseId = 29, Name = "Sandor 'The Hound' Clegane", Alive = false, EpisodeOfDeath = 72, Gender = "Male", Actor = "Rory McCann", CauseOfDeath = "Sacrifices himself into the crypt in order to kill the Mountain" },
                new Character { HouseId = 62, Name = "Missandei", Alive = false, EpisodeOfDeath = 71, Gender = "Female", Actor = "Nathalie Emmanuel", CauseOfDeath = "Beheaded by the Mountain on Cersei's orders" },
                new Character { HouseId = 32, Name = "Bronn", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Jerome Flynn", CauseOfDeath = "N/A" },
                new Character { HouseId = 20, Name = "Podrick Payne", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Daniel Portman", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Grey Worm", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Jacob Anderson", CauseOfDeath = "N/A" },
                new Character { HouseId = 25, Name = "Eddison Tollett", Alive = false, EpisodeOfDeath = 70, Gender = "Male", Actor = "Ben Crompton", CauseOfDeath = "Malled to death by wights" },
                new Character { HouseId = 62, Name = "Tormund Giantsbane", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Kristofer Hivju", CauseOfDeath = "N/A" },
                new Character { HouseId = 5, Name = "Grand Maester Pycelle", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Julian Glover", CauseOfDeath = "STABBED TO DEATH BY CHILDREN" },
                new Character { HouseId = 62, Name = "Melisandre", Alive = false, EpisodeOfDeath = 70, Gender = "Female", Actor = "Carice van Houten", CauseOfDeath = "Takes off her magical necklace that keeps her young, walks into the snow and allows herself to die" },
                new Character { HouseId = 2, Name = "Tywin Lannister", Alive = false, EpisodeOfDeath = 40, Gender = "Male", Actor = "Charles Dance", CauseOfDeath = "Killed by Tyrion Lannister" },
                new Character { HouseId = 18, Name = "Gilly", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Hannah Murray", CauseOfDeath = "N/A" },
                new Character { HouseId = 7, Name = "Margaery Tyrell", Alive = false, EpisodeOfDeath = 60, Gender = "Female", Actor = "Natalie Dormer", CauseOfDeath = "Killed by Wildfire" },
                new Character { HouseId = 5, Name = "Joffrey Baratheon", Alive = false, EpisodeOfDeath = 32, Gender = "Male", Actor = "Jack Gleeson", CauseOfDeath = "Killed by Olenna Tyrell" },
                new Character { HouseId = 1, Name = "Catelyn Stark", Alive = false, EpisodeOfDeath = 29, Gender = "Female", Actor = "Michelle Fairley", CauseOfDeath = "Killed by Walder Rivers" },
                new Character { HouseId = 33, Name = "Barristan Selmy", Alive = false, EpisodeOfDeath = 44, Gender = "Male", Actor = "Ian McElhinney", CauseOfDeath = "Killed by Sons of Harpy" },
                new Character { HouseId = 6, Name = "Stannis Baratheon", Alive = false, EpisodeOfDeath = 50, Gender = "Male", Actor = "Stephen Dillane", CauseOfDeath = "Killed by Brienne of Tarth" },
                new Character { HouseId = 62, Name = "Gendry", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Joe Dempsie", CauseOfDeath = "N/A" },
                new Character { HouseId = 1, Name = "Hodor", Alive = false, EpisodeOfDeath = 55, Gender = "Male", Actor = "Kristian Nairn", CauseOfDeath = "Torn apart by wights" },
                new Character { HouseId = 5, Name = "Qyburn", Alive = false, EpisodeOfDeath = 72, Gender = "Male", Actor = "Anton Lesser", CauseOfDeath = "Head smashed after he is thrown buy the Mountain" },
                new Character { HouseId = 62, Name = "Grenn", Alive = false, EpisodeOfDeath = 39, Gender = "Male", Actor = "Mark Stanley", CauseOfDeath = "Killed by Mag Mar Tun Doh Weg" },
                new Character { HouseId = 1, Name = "Robb Stark", Alive = false, EpisodeOfDeath = 29, Gender = "Male", Actor = "Richard Madden", CauseOfDeath = "Killed by Roose Bolton" },
                new Character { HouseId = 7, Name = "Loras Tyrell", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Finn Jones", CauseOfDeath = "Killed by Wildfire" },
                new Character { HouseId = 62, Name = "Shae", Alive = false, EpisodeOfDeath = 40, Gender = "Female", Actor = "Sibel Kekilli", CauseOfDeath = "Killed by Tyrion Lannister" },
                new Character { HouseId = 13, Name = "Ramsay Bolton", Alive = false, EpisodeOfDeath = 59, Gender = "Male", Actor = "Iwan Rheon", CauseOfDeath = "Eaten alive by his own dogs" },
                new Character { HouseId = 13, Name = "Roose Bolton", Alive = false, EpisodeOfDeath = 52, Gender = "Male", Actor = "Michael McElhatton", CauseOfDeath = "Killed by Ramsey Bolton" },
                new Character { HouseId = 34, Name = "Alliser Thorne", Alive = false, EpisodeOfDeath = 53, Gender = "Male", Actor = "Owen Teale", CauseOfDeath = "Executed by Jon Snow" },
                new Character { HouseId = 62, Name = "Daario Naharis", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Michiel Huisman", CauseOfDeath = "N/A" },
                new Character { HouseId = 7, Name = "Olenna Tyrell", Alive = false, EpisodeOfDeath = 63, Gender = "Female", Actor = "Diana Rigg", CauseOfDeath = "Poisoned by Jaime Lannister on the order of Cersei Lannister after the Lannisters defeated the Tyrells at Highgarden" },
                new Character { HouseId = 5, Name = "Tommen Baratheon", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Dean-Charles Chapman", CauseOfDeath = "Suicide by jumping out of window" },
                new Character { HouseId = 62, Name = "Ygritte", Alive = false, EpisodeOfDeath = 39, Gender = "Female", Actor = "Rose Leslie", CauseOfDeath = "Killed by Olly" },
                new Character { HouseId = 62, Name = "Jaqen H'ghar", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Tom Wlaschiha", CauseOfDeath = "N/A" },
                new Character { HouseId = 29, Name = "Gregor 'The Mountain' Clegane", Alive = false, EpisodeOfDeath = 72, Gender = "Male", Actor = "Hafþór Júlíus Björnsson", CauseOfDeath = "Killed by the Hound who sacrifices himself taking the both of them into the crypt" },
                new Character { HouseId = 62, Name = "Olly", Alive = false, EpisodeOfDeath = 53, Gender = "Male", Actor = "Brenock O'Connor", CauseOfDeath = "Executed by Jon Snow" },
                new Character { HouseId = 35, Name = "Meryn Trant", Alive = false, EpisodeOfDeath = 50, Gender = "Male", Actor = "Ian Beattie", CauseOfDeath = "Killed by Arya Stark" },
                new Character { HouseId = 62, Name = "Osha", Alive = false, EpisodeOfDeath = 54, Gender = "Female", Actor = "Natalia Tena", CauseOfDeath = "Killed by Ramsay Bolton" },
                new Character { HouseId = 11, Name = "Yara Greyjoy", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Gemma Whelan", CauseOfDeath = "N/A" },
                new Character { HouseId = 22, Name = "Meera Reed", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Ellie Kendrick", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Wun Wun", Alive = false, EpisodeOfDeath = 59, Gender = "Male", Actor = "Ian Whyte", CauseOfDeath = "Shot with and arrow by Ramsay Bolton" },
                new Character { HouseId = 2, Name = "Lancel Lannister", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Eugene Simon", CauseOfDeath = "KIlled by Wildfire" },
                new Character { HouseId = 36, Name = "Janos Slynt", Alive = false, EpisodeOfDeath = 43, Gender = "Male", Actor = "Dominic Carter", CauseOfDeath = "Executed by Jon Snow" },
                new Character { HouseId = 1, Name = "Maester Luwin", Alive = false, EpisodeOfDeath = 20, Gender = "Male", Actor = "Donald Sumpter", CauseOfDeath = "Killed by Dagmer" },
                new Character { HouseId = 62, Name = "Ros", Alive = false, EpisodeOfDeath = 26, Gender = "Female", Actor = "Esmé Bianco", CauseOfDeath = "Killed by Joffrey" },
                new Character { HouseId = 1, Name = "Rickon Stark", Alive = false, EpisodeOfDeath = 59, Gender = "Male", Actor = "Art Parkinson", CauseOfDeath = "Shot with an arrow fired by Ramsay Bolton" },
                new Character { HouseId = 37, Name = "Othell Yarwyck", Alive = false, EpisodeOfDeath = 53, Gender = "Male", Actor = "Brian Fortune", CauseOfDeath = "Executed by Jon Snow" },
                new Character { HouseId = 8, Name = "Ellaria Sand", Alive = false, EpisodeOfDeath = 72, Gender = "Female", Actor = "Indira Varma", CauseOfDeath = "Crushed in the Red Keep after Daenerys destroys the building" },
                new Character { HouseId = 62, Name = "Rodrik Cassel", Alive = false, EpisodeOfDeath = 16, Gender = "Male", Actor = "Ron Donachie", CauseOfDeath = "Killed by Theon Greyjoy" },
                new Character { HouseId = 23, Name = "Beric Dondarrion", Alive = false, EpisodeOfDeath = 70, Gender = "Female", Actor = "Richard Dormer", CauseOfDeath = "Stabbed to death by Wights saving Arya" },
                new Character { HouseId = 7, Name = "Mace Tyrell", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Roger Ashton-Griffiths", CauseOfDeath = "Killed by Wildfire" },
                new Character { HouseId = 23, Name = "Yohn Royce", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Rupert Vansittart", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Pypar", Alive = false, EpisodeOfDeath = 39, Gender = "Male", Actor = "Josef Altin", CauseOfDeath = "Killed by Ygritte" },
                new Character { HouseId = 62, Name = "Irri", Alive = false, EpisodeOfDeath = 16, Gender = "Female", Actor = "Amrita Acharia", CauseOfDeath = "Killed by Xaro Xhoan Daxos" },
                new Character { HouseId = 62, Name = "High Sparrow", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Jonathan Pryce", CauseOfDeath = "Killed by Wildfire" },
                new Character { HouseId = 17, Name = "Jeor Mormont", Alive = false, EpisodeOfDeath = 24, Gender = "Male", Actor = "James Cosmo", CauseOfDeath = "Killed by Rast" },
                new Character { HouseId = 13, Name = "Maester Wolkan", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Richard Rycroft", CauseOfDeath = "N/A" },
                new Character { HouseId = 2, Name = "Kevan Lannister", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Ian Gelder", CauseOfDeath = "Killed by Wildfire" },
                new Character { HouseId = 62, Name = "Rast", Alive = false, EpisodeOfDeath = 35, Gender = "Male", Actor = "Luke Barnes", CauseOfDeath = "Killed by Jon Snow's Wolf" },
                new Character { HouseId = 62, Name = "Hot Pie", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Ben Hawkey", CauseOfDeath = "N/A" },
                new Character { HouseId = 1, Name = "Talisa Stark", Alive = false, EpisodeOfDeath = 29, Gender = "Female", Actor = "Oona Chaplin", CauseOfDeath = "Killed by Lorthar Frey" },
                new Character { HouseId = 62, Name = "Maester Aemon", Alive = false, EpisodeOfDeath = 47, Gender = "Male", Actor = "Peter Vaughan", CauseOfDeath = "Died of natural causes" },
                new Character { HouseId = 62, Name = "The Waif", Alive = false, EpisodeOfDeath = 58, Gender = "Female", Actor = "Faye Marsay", CauseOfDeath = "Killed by Arya Stark" },
                new Character { HouseId = 62, Name = "Doreah", Alive = false, EpisodeOfDeath = 20, Gender = "Female", Actor = "Roxanne McKee", CauseOfDeath = "Locked in Xaro Xhoan Daxos' vault" },
                new Character { HouseId = 62, Name = "Qhono", Alive = false, EpisodeOfDeath = 70, Gender = "Male", Actor = "Staz Nair", CauseOfDeath = "Killed by wights during the battle of Winterfell" },
                new Character { HouseId = 1, Name = "Eddard 'Ned' Stark", Alive = false, EpisodeOfDeath = 9, Gender = "Male", Actor = "Sean Bean", CauseOfDeath = "Executed by Ilyn Payne" },
                new Character { HouseId = 62, Name = "Thoros of Myr", Alive = false, EpisodeOfDeath = 66, Gender = "Male", Actor = "Paul Kaye", CauseOfDeath = "Froze to death after being attacked by a wight bear" },
                new Character { HouseId = 6, Name = "Selyse Baratheon", Alive = false, EpisodeOfDeath = 50, Gender = "Female", Actor = "Tara Fitzgerald", CauseOfDeath = "Suicide by hanging" },
                new Character { HouseId = 21, Name = "Jojen Reed", Alive = false, EpisodeOfDeath = 40, Gender = "Male", Actor = "Thomas Brodie-Sangster", CauseOfDeath = "Killed by Wight" },
                new Character { HouseId = 6, Name = "Shireen Baratheon", Alive = false, EpisodeOfDeath = 49, Gender = "Female", Actor = "Kerry Ingram", CauseOfDeath = "Burned alive by Melisandre as a sacrafice to R'hllor" },
                new Character { HouseId = 38, Name = "Bowen Marsh", Alive = false, EpisodeOfDeath = 53, Gender = "Male", Actor = "Michael Condron", CauseOfDeath = "Executed by Jon Snow" },
                new Character { HouseId = 62, Name = "Khal Drogo", Alive = false, EpisodeOfDeath = 10, Gender = "Male", Actor = "Jason Momoa", CauseOfDeath = "Smothered by Daenerys" },
                new Character { HouseId = 11, Name = "Euron Greyjoy", Alive = false, EpisodeOfDeath = 72, Gender = "Male", Actor = "Pilou Asbæk", CauseOfDeath = "Evidently stabbed to death in the stomach by Jamie Lannister" },
                new Character { HouseId = 9, Name = "Edmure Tully", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Tobias Menzies", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Tyene Sand", Alive = false, EpisodeOfDeath = 63, Gender = "Female", Actor = "Rosabell Laurenti Sellers", CauseOfDeath = "Poisoned with a kiss by Cersei Lannister" },
                new Character { HouseId = 17, Name = "Lyanna Mormont", Alive = false, EpisodeOfDeath = 70, Gender = "Female", Actor = "Bella Ramsey", CauseOfDeath = "Crushed by a giant" },
                new Character { HouseId = 10, Name = "Robin Arryn", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Lino Facioli", CauseOfDeath = "N/A" },
                new Character { HouseId = 4, Name = "Renly Baratheon", Alive = false, EpisodeOfDeath = 15, Gender = "Male", Actor = "Gethin Anthony", CauseOfDeath = "Killed by shadow creature" },
                new Character { HouseId = 62, Name = "Locke", Alive = false, EpisodeOfDeath = 35, Gender = "Male", Actor = "Noah Taylor", CauseOfDeath = "Killed by Bran Stark" },
                new Character { HouseId = 62, Name = "Obara Sand", Alive = false, EpisodeOfDeath = 62, Gender = "Female", Actor = "Keisha Castle-Hughes", CauseOfDeath = "Stabbed by Euron Greyjoy" },
                new Character { HouseId = 62, Name = "Hizdahr zo Loraq", Alive = false, EpisodeOfDeath = 49, Gender = "Male", Actor = "Joel Fry", CauseOfDeath = "Killed by Son of Harpy" },
                new Character { HouseId = 62, Name = "Nymeria Sand", Alive = false, EpisodeOfDeath = 62, Gender = "Female", Actor = "Jessica Henwick", CauseOfDeath = "Strangled by Euron Greyjoy" },
                new Character { HouseId = 62, Name = "Septa Unella", Alive = false, EpisodeOfDeath = 72, Gender = "Female", Actor = "Hannah Waddingham", CauseOfDeath = "" },
                new Character { HouseId = 62, Name = "Myranda", Alive = false, EpisodeOfDeath = 50, Gender = "Female", Actor = "Charlotte Hope", CauseOfDeath = "Killed by Theon Greyjoy" },
                new Character { HouseId = 62, Name = "Kovarro", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Steven Cole", CauseOfDeath = "N/A" },
                new Character { HouseId = 5, Name = "Myrcella Baratheon", Alive = false, EpisodeOfDeath = 50, Gender = "Female", Actor = "Aimee Richardson", CauseOfDeath = "Poisoned with the Long Fairwell after being kissed by Ellaria Sand" },
                new Character { HouseId = 62, Name = "Marei", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Josephine Gillan", CauseOfDeath = "N/A" },
                new Character { HouseId = 5, Name = "Robert Baratheon", Alive = false, EpisodeOfDeath = 7, Gender = "Male", Actor = "Mark Addy", CauseOfDeath = "Killed by a boar" },
                new Character { HouseId = 8, Name = "Oberyn Martell", Alive = false, EpisodeOfDeath = 38, Gender = "Male", Actor = "Pedro Pascal", CauseOfDeath = "Killed by The Mountain" },
                new Character { HouseId = 62, Name = "Yoren", Alive = false, EpisodeOfDeath = 13, Gender = "Male", Actor = "Francis Magee", CauseOfDeath = "Killed by Armory Lorch" },
                new Character { HouseId = 9, Name = "Brynden 'Blackfish' Tully", Alive = false, EpisodeOfDeath = 58, Gender = "Male", Actor = "Clive Russell", CauseOfDeath = "Killed by Lannister Soldier" },
                new Character { HouseId = 62, Name = "Olyvar", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Will Tudor", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Rakharo", Alive = false, EpisodeOfDeath = 12, Gender = "Male", Actor = "Elyes Gabel", CauseOfDeath = "Killed by Dothrakis" },
                new Character { HouseId = 62, Name = "Bernadette", Alive = false, EpisodeOfDeath = null, Gender = "Female", Actor = "Sara Dylan", CauseOfDeath = "Likely was killed during the Battle of King's Landing" },
                new Character { HouseId = 12, Name = "Walder Frey", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "David Bradley", CauseOfDeath = "Killed by Arya Stark" },
                new Character { HouseId = 1, Name = "Benjen Stark", Alive = false, EpisodeOfDeath = 66, Gender = "Male", Actor = "Joseph Mawle", CauseOfDeath = "Overwhelmed fighting wights" },
                new Character { HouseId = 62, Name = "Orell", Alive = false, EpisodeOfDeath = 29, Gender = "Male", Actor = "Mackenzie Crook", CauseOfDeath = "Killed by Jon Snow" },
                new Character { HouseId = 62, Name = "Areo Hotah", Alive = false, EpisodeOfDeath = 51, Gender = "Male", Actor = "Deobia Oparei", CauseOfDeath = "Stabbed in the back by Tyene Sand" },
                new Character { HouseId = 62, Name = "Septa Mordane", Alive = false, EpisodeOfDeath = 8, Gender = "Female", Actor = "Susan Brown", CauseOfDeath = "Killed by House Lannister men" },
                new Character { HouseId = 62, Name = "Black Walder Rivers", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Tim Plester", CauseOfDeath = "Killed by Arya Stark" },
                new Character { HouseId = 62, Name = "Qotho", Alive = false, EpisodeOfDeath = 9, Gender = "Male", Actor = "Dar Salim", CauseOfDeath = "Killed by Jorah Mormont" },
                new Character { HouseId = 39, Name = "Dontos Hollard", Alive = false, EpisodeOfDeath = 33, Gender = "Male", Actor = "Tony Way", CauseOfDeath = "Killed by Petyr Baelish's men" },
                new Character { HouseId = 62, Name = "Anguy", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Philip McGinley", CauseOfDeath = "N/A" },
                new Character { HouseId = 19, Name = "Alys Karstark", Alive = false, EpisodeOfDeath = 73, Gender = "Female", Actor = "Megan Parkinson", CauseOfDeath = "Killed by wights while defeneding Bran Stark durinng the battle of Winterfell" },
                new Character { HouseId = 3, Name = "Viserys Targaryen", Alive = false, EpisodeOfDeath = 6, Gender = "Male", Actor = "Harry Lloyd", CauseOfDeath = "Killed by Khal Drogo" },
                new Character { HouseId = 40, Name = "Jory Cassel", Alive = false, EpisodeOfDeath = 5, Gender = "Male", Actor = "Jamie Sives", CauseOfDeath = "Killed by Jamie Lannister" },
                new Character { HouseId = 10, Name = "Lysa Arryn", Alive = false, EpisodeOfDeath = 37, Gender = "Female", Actor = "Kate Dickie", CauseOfDeath = "Pushed through moon door by Littlefinger" },
                new Character { HouseId = 62, Name = "Mance Rayder", Alive = false, EpisodeOfDeath = 41, Gender = "Male", Actor = "Ciarán Hinds", CauseOfDeath = "Mercy Killed by Jon Snow" },
                new Character { HouseId = 62, Name = "Craster", Alive = false, EpisodeOfDeath = 24, Gender = "Male", Actor = "Robert Pugh", CauseOfDeath = "Stabbed in the throat Karl Tanner during a mutiny" },
                new Character { HouseId = 8, Name = "Doran Martell", Alive = false, EpisodeOfDeath = 51, Gender = "Male", Actor = "Alexander Siddig", CauseOfDeath = "Killed by Ellaria Sand" },
                new Character { HouseId = 62, Name = "Xaro Xhoan Daxos", Alive = false, EpisodeOfDeath = 20, Gender = "Male", Actor = "Nonso Anozie", CauseOfDeath = "Locked in his own vault" },
                new Character { HouseId = 18, Name = "Randyll Tarly", Alive = false, EpisodeOfDeath = 65, Gender = "Male", Actor = "James Faulkner", CauseOfDeath = "Burned alive by a dragon" },
                new Character { HouseId = 25, Name = "Robett Glover", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Tim McInnerny", CauseOfDeath = "N/A" },
                new Character { HouseId = 19, Name = "Rickard Karstark", Alive = false, EpisodeOfDeath = 25, Gender = "Male", Actor = "John Stahl", CauseOfDeath = "Beheaded by Rob Stark for treason" },
                new Character { HouseId = 62, Name = "Dagmer Cleftjaw", Alive = false, EpisodeOfDeath = 20, Gender = "Male", Actor = "Ralph Ineson", CauseOfDeath = "Flayed alive by Ramsay Snow following the Sack on Winterfell" },
                new Character { HouseId = 13, Name = "Walda Bolton", Alive = false, EpisodeOfDeath = 52, Gender = "Female", Actor = "Elizabeth Webster", CauseOfDeath = "Killed by Ramsey Bolton" },
                new Character { HouseId = 8, Name = "Trystane Martell", Alive = false, EpisodeOfDeath = 51, Gender = "Male", Actor = "Toby Sebastian", CauseOfDeath = "Killed by Obara Sand" },
                new Character { HouseId = 62, Name = "The Night King", Alive = false, EpisodeOfDeath = 70, Gender = "Male", Actor = "Vladimir 'Furdo' Furdik", CauseOfDeath = "Stabbed with a Valyrian steel blade by Arya Stark" },
                new Character { HouseId = 62, Name = "Archmaester Ebrose", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Jim Broadbent", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Tycho Nestoris", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Mark Gatiss", CauseOfDeath = "N/A" },
                new Character { HouseId = 11, Name = "Balon Greyjoy", Alive = false, EpisodeOfDeath = 52, Gender = "Male", Actor = "Patrick Malahide", CauseOfDeath = "Thrown from a bridge by Euron Greyjoy" },
                new Character { HouseId = 62, Name = "Pyat Pree", Alive = false, EpisodeOfDeath = 20, Gender = "Male", Actor = "Ian Hanmore", CauseOfDeath = "Killed by Daenery's Dragons" },
                new Character { HouseId = 62, Name = "Styr", Alive = false, EpisodeOfDeath = 39, Gender = "Male", Actor = "Yuri Kolokolnikov", CauseOfDeath = "Killed by Jon Snow" },
                new Character { HouseId = 62, Name = "Yezzan zo Qaggaz", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Enzo Cilenti", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Karl Tanner", Alive = false, EpisodeOfDeath = 35, Gender = "Male", Actor = "Burn Gorman", CauseOfDeath = "Killed by Jon Snow" },
                new Character { HouseId = 20, Name = "Ilyn Payne", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Wilko Johnson", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Marillion", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Emun Elliott", CauseOfDeath = "N/A" },
                new Character { HouseId = 18, Name = "Dickon Tarly", Alive = false, EpisodeOfDeath = 65, Gender = "Male", Actor = "Tom Hopper", CauseOfDeath = "Burned alive by a dragon" },
                new Character { HouseId = 62, Name = "Qhorin Halfhand", Alive = false, EpisodeOfDeath = 20, Gender = "Male", Actor = "Simon Armstrong", CauseOfDeath = "Killed by Jon Snow" },
                new Character { HouseId = 12, Name = "Lothar Frey", Alive = false, EpisodeOfDeath = 60, Gender = "Male", Actor = "Daniel Tuite", CauseOfDeath = "Killed by Arya Stark" },
                new Character { HouseId = 62, Name = "Rorge", Alive = false, EpisodeOfDeath = 37, Gender = "Male", Actor = "Andy Beckwith", CauseOfDeath = "Killed by Arya Stark" },
                new Character { HouseId = 62, Name = "Lommy Greenhands", Alive = false, EpisodeOfDeath = 13, Gender = "Male", Actor = "Eros Vlahos", CauseOfDeath = "Killed by Polliver" },
                new Character { HouseId = 30, Name = "Matthos Seaworth", Alive = false, EpisodeOfDeath = 19, Gender = "Male", Actor = "Kerr Logan", CauseOfDeath = "Killed by Wildfire explosion" },
                new Character { HouseId = 62, Name = "Armeca", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Sahara Knite", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Royal Steward", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Robert Sterne", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Black Lorren", Alive = false, EpisodeOfDeath = 20, Gender = "Male", Actor = "Forbes KB", CauseOfDeath = "Flayed alive by Ramsay Snow following the Sack on Winterfell" },
                new Character { HouseId = 41, Name = "Amory Lorch", Alive = false, EpisodeOfDeath = 16, Gender = "Male", Actor = "Fintan McKeown", CauseOfDeath = "Shot in the neck with a dart tipped with Wolfsbane by Jaqen H'ghar" },
                new Character { HouseId = 62, Name = "Biter", Alive = false, EpisodeOfDeath = 37, Gender = "Male", Actor = "Gerard Jordan", CauseOfDeath = "Killed by The Hound" },
                new Character { HouseId = 62, Name = "Timett", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Tobias Winter", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Steelshanks Walton", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Jamie Michie", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Izembaro", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Richard E. Grant", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Lady Crane", Alive = false, EpisodeOfDeath = 58, Gender = "Female", Actor = "Essie Davis", CauseOfDeath = "Killed by the Waif" },
                new Character { HouseId = 62, Name = "Spice King", Alive = false, EpisodeOfDeath = 17, Gender = "Male", Actor = "Nicholas Blane", CauseOfDeath = "Throat slit by a duplicate of Pyat Pree" },
                new Character { HouseId = 62, Name = "Three-Eyed Raven", Alive = false, EpisodeOfDeath = 55, Gender = "Male", Actor = "Max von Sydow", CauseOfDeath = "Killed by The Night King" },
                new Character { HouseId = 62, Name = "Syrio Forel", Alive = false, EpisodeOfDeath = 8, Gender = "Male", Actor = "Miltos Yerolemou", CauseOfDeath = "Killed by House Lannister men" },
                new Character { HouseId = 62, Name = "Harrag", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Brendan Cowell", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Salladhor Saan", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Lucian Msamati", CauseOfDeath = "N/A" },
                new Character { HouseId = 16, Name = "Greatjon Umber", Alive = false, EpisodeOfDeath = 53, Gender = "Male", Actor = "Clive Mantle", CauseOfDeath = "Died during the War of the Five Kings" },
                new Character { HouseId = 62, Name = "Camello", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Kevin Eldon", CauseOfDeath = "N/A" },
                new Character { HouseId = 19, Name = "Harald Karstark", Alive = false, EpisodeOfDeath = null, Gender = "Male", Actor = "Paul Rattray", CauseOfDeath = "Died during at the Battle of the Bastards" },
                new Character { HouseId = 62, Name = "Bobono", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Leigh Gill", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Razdal mo Eraz", Alive = false, EpisodeOfDeath = 59, Gender = "Male", Actor = "George Georgiou", CauseOfDeath = "Killed by Grey Worm" },
                new Character { HouseId = 62, Name = "Lhara", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Sarine Sofair", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Clarenzo", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Rob Callender", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Thenn Warg", Alive = false, EpisodeOfDeath = 39, Gender = "Male", Actor = "Joseph Gatt", CauseOfDeath = "Killed by Samwell Tarly" },
                new Character { HouseId = 62, Name = "Mirri Maz Duur", Alive = false, EpisodeOfDeath = 10, Gender = "Female", Actor = "Mia Soteriou", CauseOfDeath = "Burned alive by Dragon" },
                new Character { HouseId = 62, Name = "Polliver", Alive = false, EpisodeOfDeath = 31, Gender = "Male", Actor = "Andy Kellegher", CauseOfDeath = "Killed by Arya Stark" },
                new Character { HouseId = 2, Name = "Alton Lannister", Alive = false, EpisodeOfDeath = 17, Gender = "Male", Actor = "Karl Davies", CauseOfDeath = "Killed by Jamie Lannister" },
                new Character { HouseId = 62, Name = "Khal Moro", Alive = false, EpisodeOfDeath = 54, Gender = "Male", Actor = "Joseph Naufahu", CauseOfDeath = "Burned alive by Dragon" },
                new Character { HouseId = 16, Name = "Ned Umber", Alive = false, EpisodeOfDeath = 68, Gender = "Male", Actor = "Harry Grasby", CauseOfDeath = "Killed by Whitewalkers" },
                new Character { HouseId = 62, Name = "Kraznys mo Nakloz", Alive = false, EpisodeOfDeath = 24, Gender = "Male", Actor = "Dan Hildebrand", CauseOfDeath = "Killed by Dragon" },
                new Character { HouseId = 62, Name = "Mossador", Alive = false, EpisodeOfDeath = 42, Gender = "Male", Actor = "Reece Noi", CauseOfDeath = "Executed by Daario Naharis" },
                new Character { HouseId = 62, Name = "Rattleshirt", Alive = false, EpisodeOfDeath = 48, Gender = "Male", Actor = "Edward Dogliani", CauseOfDeath = "Beaten to death with his own staff by Tormund" },
                new Character { HouseId = 62, Name = "Vala", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Meena Rayann", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Daisy", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Maisie Dee", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Silk King", Alive = false, EpisodeOfDeath = 17, Gender = "Male", Actor = "Slavko Juraga", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Aggo", Alive = false, EpisodeOfDeath = 54, Gender = "Male", Actor = "Chuku Modu", CauseOfDeath = "Stabbed in the back by Daario Naharis" },
                new Character { HouseId = 62, Name = "Frances", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Annette Hannah", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Hallyne", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Roy Dotrice", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Harry Strickland", Alive = false, EpisodeOfDeath = 72, Gender = "Male", Actor = "Marc Rissmann", CauseOfDeath = "Speared in the back by Grey Worm in the siege of King's Landing" },
                new Character { HouseId = 62, Name = "Illyrio Mopatis", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Roger Allam", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Lem Lemoncloak", Alive = false, EpisodeOfDeath = 58, Gender = "Male", Actor = "Jóhannes Haukur Jóhannesson", CauseOfDeath = "Killed by Sandor Clegane" },
                new Character { HouseId = 16, Name = "Smalljon Umber", Alive = false, EpisodeOfDeath = 59, Gender = "Male", Actor = "Dean Jagger", CauseOfDeath = "Killed by Tormund" },
                new Character { HouseId = 62, Name = "Martha", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Bronte Carmichael", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Mord", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Ciaran Bermingham", CauseOfDeath = "N/A" },
                new Character { HouseId = 11, Name = "Aeron Greyjoy", Alive = false, EpisodeOfDeath = null, Gender = "Male", Actor = "Michael Feast", CauseOfDeath = "Died sometime before 305 AC" },
                new Character { HouseId = 62, Name = "Dim Dalba", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Murray McArthur", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Belicho Paenymion", Alive = false, EpisodeOfDeath = 59, Gender = "Male", Actor = "Eddie Jackson", CauseOfDeath = "Killed by Grey Worm" },
                new Character { HouseId = 62, Name = "Fergus", Alive = false, EpisodeOfDeath = 70, Gender = "Male", Actor = "Seamus O'Hara", CauseOfDeath = "Killed by the Night King's forces" },
                new Character { HouseId = 62, Name = "Gatins", Alive = false, EpisodeOfDeath = 58, Gender = "Male", Actor = "Ricky Champ", CauseOfDeath = "Killed by Sandor Clegane" },
                new Character { HouseId = 62, Name = "Teela", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Bea Glancy", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Old Nan", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Margaret John", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Morgan", Alive = false, EpisodeOfDeath = 58, Gender = "Male", Actor = "Ian Davies", CauseOfDeath = "Killed by Sandor Clegane" },
                new Character { HouseId = 62, Name = "Malko", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Adewale Akinnuoye-Agbaje", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Bianca", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Eline Powell", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Vardis Egen", Alive = false, EpisodeOfDeath = 6, Gender = "Male", Actor = "Brendan McCormack", CauseOfDeath = "Killed by Bronn" },
                new Character { HouseId = 62, Name = "Shagga", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Mark Lewis Jones", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Quaithe", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Laura Pradelska", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Hugh of the Vale", Alive = false, EpisodeOfDeath = 4, Gender = "Male", Actor = "Jefferson Hall", CauseOfDeath = "Killed by The Mountain" },
                new Character { HouseId = 62, Name = "Morag", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Deirdre Monaghan", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Todder", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Will O'Connell", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Johnna", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Ali Lyons", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Willa", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Karla Lyons", CauseOfDeath = "N/A" },
                new Character { HouseId = 12, Name = "Lady Kitty Frey", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Lucy Hayes", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Baby Sam", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Finn Watson", CauseOfDeath = "N/A" },
                new Character { HouseId = 1, Name = "Lyanna Stark", Alive = false, EpisodeOfDeath = null, Gender = "Female", Actor = "Aisling Franciosi", CauseOfDeath = "Died giving birth to Aegon Targaryen" },
                new Character { HouseId = 62, Name = "Farlen", Alive = false, EpisodeOfDeath = 17, Gender = "Male", Actor = "Peter Ballance", CauseOfDeath = "Killed during the Sack of Winterfell" },
                new Character { HouseId = 42, Name = "Donnel Waynwood", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Alisdair Simpson", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Drennan", Alive = false, EpisodeOfDeath = 16, Gender = "Male", Actor = "David Coakley", CauseOfDeath = "Killed by Osha" },
                new Character { HouseId = 62, Name = "Sissy", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Jane McGrath", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Zanrush", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Gerald Lepkowski", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Ornela", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Hannah John-Kamen", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Young Nan", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Annette Tierney", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Kurleket", Alive = false, EpisodeOfDeath = 5, Gender = "Male", Actor = "Kevin Keenan", CauseOfDeath = "Killed by hill tribesman" },
                new Character { HouseId = 62, Name = "The Tickler", Alive = false, EpisodeOfDeath = 15, Gender = "Male", Actor = "Anthony Morris", CauseOfDeath = "Killed by Jaqen H'ghar" },
                new Character { HouseId = 62, Name = "Ghita", Alive = false, EpisodeOfDeath = 46, Gender = "Female", Actor = "Hattie Gotobed", CauseOfDeath = "Poisoned with water from The House of Black and White by Arya" },
                new Character { HouseId = 62, Name = "Wyllis", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Sam Coleman", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Greizhen mo Ullhor", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Cliff Barry", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Mole's Town Whore", Alive = false, EpisodeOfDeath = 38, Gender = "Female", Actor = "Lois Winstone", CauseOfDeath = "Killed by Ygritte" },
                new Character { HouseId = 43, Name = "Willis Wode", Alive = false, EpisodeOfDeath = 5, Gender = "Male", Actor = "Ryan McKenna", CauseOfDeath = "Killed by hill tribesman" },
                new Character { HouseId = 62, Name = "Jacks", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Paul Caddell", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Ternesio Terys", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Gary Oliver", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Mhaegen", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Antonia Christophers", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Quent", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Aidan Crowe", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Kayla", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Pixie Le Knot", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Tobho Mott", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Andrew Wilde", CauseOfDeath = "N/A" },
                new Character { HouseId = 2, Name = "Willem Lannister", Alive = false, EpisodeOfDeath = 25, Gender = "Male", Actor = "Timothy Gibbons", CauseOfDeath = "Killed by Richard Karstark" },
                new Character { HouseId = 62, Name = "Arthur", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Nathanael Saleh", CauseOfDeath = "N/A" },
                new Character { HouseId = 12, Name = "Joyeuse Frey", Alive = false, EpisodeOfDeath = 29, Gender = "Female", Actor = "Kelly Long", CauseOfDeath = "Killed by Catelyn Stark" },
                new Character { HouseId = 62, Name = "Tommy", Alive = false, EpisodeOfDeath = 22, Gender = "Male", Actor = "Tommy Dunne", CauseOfDeath = "Presumably killed by Ramsay Bolton's men during the Sack of Winterfell" },
                new Character { HouseId = 44, Name = "Leo Lefford", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Vinnie McCabe", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Brother Ray", Alive = false, EpisodeOfDeath = 57, Gender = "Male", Actor = "Ian McShane", CauseOfDeath = "Killed by a rogue member of the Brotherhood without Banners" },
                new Character { HouseId = 62, Name = "Nora", Alive = false, EpisodeOfDeath = 72, Gender = "Female", Actor = "Laura Elphinstone", CauseOfDeath = "Burned alive by Drogon" },
                new Character { HouseId = 62, Name = "Xela", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Alexis Raben", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Karsi", Alive = false, EpisodeOfDeath = 48, Gender = "Female", Actor = "Birgitte Hjort Sørensen", CauseOfDeath = "Killed by a pack of child-wights" },
                new Character { HouseId = 62, Name = "Loboda", Alive = false, EpisodeOfDeath = 48, Gender = "Male", Actor = "Zachary Baharov", CauseOfDeath = "Killed by White Walker" },
                new Character { HouseId = 14, Name = "Imry Florent", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Gordon Mahon", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Koner", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Joseph Quinn", CauseOfDeath = "N/A" },
                new Character { HouseId = 45, Name = "Mandon Moore", Alive = false, EpisodeOfDeath = 19, Gender = "Male", Actor = "James Doran", CauseOfDeath = "Killed by Podrick" },
                new Character { HouseId = 62, Name = "Jhiqui", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Sarita Piotrowski", CauseOfDeath = "N/A" },
                new Character { HouseId = 18, Name = "Melessa Tarly", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Samantha Spiro", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Winterfell Local", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Breige Roche", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Will", Alive = false, EpisodeOfDeath = 1, Gender = "Male", Actor = "Bronson Webb", CauseOfDeath = "Executed by Ned Stark" },
                new Character { HouseId = 62, Name = "Lord of Bones", Alive = false, EpisodeOfDeath = 48, Gender = "Male", Actor = "Ross O'Hennessy", CauseOfDeath = "Killed by Tormund" },
                new Character { HouseId = 62, Name = "Lord Une", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Michael Benbaruk", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Mycah", Alive = false, EpisodeOfDeath = 2, Gender = "Male", Actor = "Rhodri Hosking", CauseOfDeath = "Killed by The Hound" },
                new Character { HouseId = 10, Name = "Jon Arryn", Alive = false, EpisodeOfDeath = 1, Gender = "Male", Actor = "John Standing", CauseOfDeath = "Poisoned by Lysa" },
                new Character { HouseId = 62, Name = "Mero", Alive = false, EpisodeOfDeath = 28, Gender = "Male", Actor = "Mark Killeen", CauseOfDeath = "Killed by Daario Naharis" },
                new Character { HouseId = 22, Name = "Waymar Royce", Alive = false, EpisodeOfDeath = 1, Gender = "Male", Actor = "Rob Ostlere", CauseOfDeath = "Killed by White Walker" },
                new Character { HouseId = 62, Name = "Prendahl na Ghezn", Alive = false, EpisodeOfDeath = 28, Gender = "Male", Actor = "Ramon Tikaram", CauseOfDeath = "Killed by Daario Naharis" },
                new Character { HouseId = 62, Name = "Gared", Alive = false, EpisodeOfDeath = 1, Gender = "Male", Actor = "Dermot Keaney", CauseOfDeath = "Killed by White Walker" },
                new Character { HouseId = 62, Name = "Maester Cressen", Alive = false, EpisodeOfDeath = 11, Gender = "Male", Actor = "Oliver Ford Davies", CauseOfDeath = "Suicide by Poison" },
                new Character { HouseId = 62, Name = "Maggy", Alive = false, EpisodeOfDeath = null, Gender = "Female", Actor = "Jodhi May", CauseOfDeath = "Killed by Randyll Tarly near Horn Hill" },
                new Character { HouseId = 12, Name = "Roslin Frey", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Alexandra Dowling", CauseOfDeath = "N/A" },
                new Character { HouseId = 42, Name = "Anya Waynwood", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Paola Dionisotti", CauseOfDeath = "N/A" },
                 new Character { HouseId = 3, Name = "Rhaegar Targaryen", Alive = false, EpisodeOfDeath = null, Gender = "Male", Actor = "Wilf Scolding", CauseOfDeath = "Killed during the Battle of the Trident" },
                new Character { HouseId = 62, Name = "Sarra", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Danielle Galligan", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Joss", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "James McKenzie Robinson", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "High Septon Maynard", Alive = false, EpisodeOfDeath = 16, Gender = "Male", Actor = "Tom Chadbon", CauseOfDeath = "Killed by rioters" },
                new Character { HouseId = 12, Name = "Merry Frey", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Grace Hendy", CauseOfDeath = "N/A" },
                new Character { HouseId = 46, Name = "Ralf Kenning", Alive = false, EpisodeOfDeath = 38, Gender = "Male", Actor = "Grahame Fox", CauseOfDeath = "Killed by Adrack Humble" },
                new Character { HouseId = 3, Name = "Aerys Targaryen", Alive = false, EpisodeOfDeath = 56, Gender = "Male", Actor = "David Rintoul", CauseOfDeath = "Killed by Jamie Lannister" },
                new Character { HouseId = 62, Name = "Crayah", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Lucy Aarden", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Varly", Alive = false, EpisodeOfDeath = 7, Gender = "Male", Actor = "Graham Charles", CauseOfDeath = "Killed by the City Watch during the Massacre in the Red Keep" },
                new Character { HouseId = 62, Name = "Dirah", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Marina Lawrence-Mahrra", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Fennesz", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Trevor Allan Davies", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Tansy", Alive = false, EpisodeOfDeath = 32, Gender = "Female", Actor = "Jazzy De Lisser", CauseOfDeath = "Killed by Ramsey's Dogs" },
                new Character { HouseId = 18, Name = "Talla Tarly", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Rebecca Benson", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Ash", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Yousef 'Joe' Sweid", CauseOfDeath = "N/A" },
                new Character { HouseId = 47, Name = "Jaremy Rykker", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Jeffrey O'Brien", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Rennick", Alive = false, EpisodeOfDeath = 14, Gender = "Male", Actor = "David Fynn", CauseOfDeath = "Killed by Rob Stark's Wolf" },
                new Character { HouseId = 48, Name = "Wendel Manderly", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Oddie Braddell", CauseOfDeath = "N/A" },
                new Character { HouseId = 49, Name = "Adrack Humble", Alive = false, EpisodeOfDeath = 38, Gender = "Male", Actor = "Jody Halse", CauseOfDeath = "Killed by Ramsey Snow's men" },
                new Character { HouseId = 62, Name = "Kesh", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Michael Heath", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Riddell", Alive = false, EpisodeOfDeath = 58, Gender = "Male", Actor = "Ross McKinney", CauseOfDeath = "Killed by Sandor Clegane" },
                new Character { HouseId = 19, Name = "Torrhen Karstark", Alive = false, EpisodeOfDeath = 17, Gender = "Male", Actor = "Tyrone McElhennon", CauseOfDeath = "Killed by Jamie Lannister" },
                new Character { HouseId = 62, Name = "Kinvara", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Ania Bukstein", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Steve", Alive = false, EpisodeOfDeath = 58, Gender = "Male", Actor = "Steve Love", CauseOfDeath = "Killed by Sandor Clegane" },
                new Character { HouseId = 62, Name = "Tomard", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Phil Dixon", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Stiv", Alive = false, EpisodeOfDeath = 6, Gender = "Male", Actor = "Stephen Don", CauseOfDeath = "Killed by Theon Greyjoy" },
                new Character { HouseId = 62, Name = "Leaf", Alive = false, EpisodeOfDeath = 55, Gender = "Female", Actor = "Octavia Selena Alexandru", CauseOfDeath = "Suicide by activating an explosive device taking out wights" },
                new Character { HouseId = 50, Name = "Vance Corbray", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Richard Doubleday", CauseOfDeath = "N/A" },
                new Character { HouseId = 14, Name = "Axell Florent", Alive = false, EpisodeOfDeath = 32, Gender = "Male", Actor = "James McHale", CauseOfDeath = "Burned alive by Melisandre" },
                new Character { HouseId = 62, Name = "Khal Forzho", Alive = false, EpisodeOfDeath = 54, Gender = "Male", Actor = "Tamer Hassan", CauseOfDeath = "Burned alive by Daenerys" },
                new Character { HouseId = 62, Name = "Mirelle", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Elisa Lasowski", CauseOfDeath = "N/A" },
                new Character { HouseId = 51, Name = "Lord Blackmont", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Daniel Rabin", CauseOfDeath = "N/A" },
                new Character { HouseId = 12, Name = "Stevron Frey", Alive = false, EpisodeOfDeath = 61, Gender = "Male", Actor = "Colin Carnegie", CauseOfDeath = "Poisoned by Arya Stark" },
                new Character { HouseId = 52, Name = "Eon Hunter", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Barrington Cullen", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Gerald", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Ken Fletcher", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Kegs", Alive = false, EpisodeOfDeath = 38, Gender = "Male", Actor = "Tim Landers", CauseOfDeath = "Killed by wildling during the Sack of Mole's Town" },
                new Character { HouseId = 62, Name = "Derek", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Ian Lloyd Anderson", CauseOfDeath = "N/A" },
                new Character { HouseId = 53, Name = "Lollys Stokeworth", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Elizabeth Cadwallader", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Ryger Rivers", Alive = false, EpisodeOfDeath = 61, Gender = "Male", Actor = "Bryan McCaugherty", CauseOfDeath = "Poisoned by Arya Stark" },
                new Character { HouseId = 62, Name = "Colen of Greenpools", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Darren Killeen", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Black Jack Bulwer", Alive = false, EpisodeOfDeath = 38, Gender = "Male", Actor = "Cormac McDonagh", CauseOfDeath = "Killed by wildling during the Sack of Mole's Town" },
                new Character { HouseId = 28, Name = "Ser Endrew Tarth", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Dez McMahon", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Brant", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Jonathan Byrne", CauseOfDeath = "N/A" },
                new Character { HouseId = 1, Name = "Rickard Stark", Alive = false, EpisodeOfDeath = null, Gender = "Male", Actor = "Wayne Foskett", CauseOfDeath = "Burned alive by Rossart with wildfire at the order of King Aerys II Targaryen" },
                new Character { HouseId = 62, Name = "Mully", Alive = false, EpisodeOfDeath = 38, Gender = "Male", Actor = "Andy Moore", CauseOfDeath = "Killed by wildling during the Sack of Mole's Town" },
                new Character { HouseId = 54, Name = "Arthur Dayne", Alive = false, EpisodeOfDeath = 53, Gender = "Male", Actor = "Luke Roberts", CauseOfDeath = "Killed by Ned Stark" },
                new Character { HouseId = 2, Name = "Reginald Lannister", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Patrick FitzSymons", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Clea", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Gwyneth Keyworth", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Brusco", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Garry Mountaine", CauseOfDeath = "N/A" },
                new Character { HouseId = 55, Name = "Gerold Hightower", Alive = false, EpisodeOfDeath = 53, Gender = "Male", Actor = "Eddie Eyre", CauseOfDeath = "Killed by Ned Stark" },
                new Character { HouseId = 62, Name = "Iggo", Alive = false, EpisodeOfDeath = 54, Gender = "Male", Actor = "Deon Lee-Williams", CauseOfDeath = "Daario Naharis" },
                new Character { HouseId = 56, Name = "Denys Mallister", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "J.J. Murphy", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Khal Brozho", Alive = false, EpisodeOfDeath = 54, Gender = "Male", Actor = "Elie Haddad", CauseOfDeath = "Burned alive by Daenerys Targaryen" },
                new Character { HouseId = 57, Name = "Jonos Bracken", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Gerry O'Brien", CauseOfDeath = "N/A" },
                new Character { HouseId = 58, Name = "Desmond Crakehall", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Maro Drobnic", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Guymon", Alive = false, EpisodeOfDeath = 33, Gender = "Male", Actor = "Jem Wall", CauseOfDeath = "Killed by Ygritte" },
                new Character { HouseId = 59, Name = "Melara Hetherspoon", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Isabella Steinbarth", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Khal Rhalko", Alive = false, EpisodeOfDeath = 54, Gender = "Male", Actor = "Andrei Claude", CauseOfDeath = "Burned alive by Daenerys Targaryen" },
                new Character { HouseId = 62, Name = "Septa Moelle", Alive = false, EpisodeOfDeath = 60, Gender = "Female", Actor = "Maggie Hayes", CauseOfDeath = "Burned alive during the Destruction of the Great Sept of Baelor" },
                new Character { HouseId = 62, Name = "White Rat", Alive = false, EpisodeOfDeath = 41, Gender = "Male", Actor = "Marcos James", CauseOfDeath = "Killed by a member in the Son's of the Harpy" },
                new Character { HouseId = 62, Name = "Anara", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Ollie Kram", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Khal Qorro", Alive = false, EpisodeOfDeath = 54, Gender = "Male", Actor = "Darius Dar Khan", CauseOfDeath = "Burned alive by Daenerys Targaryen" },
                new Character { HouseId = 60, Name = "Addam Marbrand", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "B.J. Hogg", CauseOfDeath = "N/A" },
                new Character { HouseId = 61, Name = "Vayon Poole", Alive = false, EpisodeOfDeath = 8, Gender = "Male", Actor = "Matthew Scurfield", CauseOfDeath = "Killed by House Lannister men" },
                new Character { HouseId = 62, Name = "Strong Sam Stone", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Allan Gildea", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Septa Scolera", Alive = false, EpisodeOfDeath = 50, Gender = "Female", Actor = "Mary Jordan", CauseOfDeath = "Killed during the Destruction of the Great Sept of Baelor" },
                new Character { HouseId = 62, Name = "Brea", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Gemita Samarra", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Masha Heddle", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Susie Kelly", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Aya", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Aifric O'Donnell", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Rhaego", Alive = false, EpisodeOfDeath = 10, Gender = "Female", Actor = "Wren Ros Elliot-Sloan", CauseOfDeath = "Stillborn, caused by Mirri Maz Duur's blood magic" },
                new Character { HouseId = 62, Name = "Maester Helliweg", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Joe Hewetson", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Genna", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Kylie Harris", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Maester Caleotte", Alive = false, EpisodeOfDeath = 51, Gender = "Male", Actor = "Colin Azzopardi", CauseOfDeath = "Killed by Tyene Sand" },
                new Character { HouseId = 62, Name = "Chella", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Natalia Lee", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Gordy", Alive = false, EpisodeOfDeath = 50, Gender = "Male", Actor = "Tristan McConnell", CauseOfDeath = "Stabbed in the neck with Lightbringer by Stannis Baratheon" },
                new Character { HouseId = 48, Name = "Wyman Manderly", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Sean Blowers", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Lord Portan", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Gordon Fulton", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Simpson", Alive = false, EpisodeOfDeath = 50, Gender = "Male", Actor = "Laurence O'Fuarain", CauseOfDeath = "Stabbed in the neck with Lightbringer by Stannis Baratheon" },
                new Character { HouseId = 62, Name = "The Bear", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Bart the Bear", CauseOfDeath = "N/A" },
                new Character { HouseId = 25, Name = "Lord Galbart Glover", Alive = false, EpisodeOfDeath = null, Gender = "Male", Actor = "Mark Coney", CauseOfDeath = "Died during the War of the Five Kings" },
                new Character { HouseId = 62, Name = "Mikken", Alive = false, EpisodeOfDeath = 22, Gender = "Male", Actor = "Boyd Rankin", CauseOfDeath = "Likely killed in the Sack of Winterfell by Ramsar Bolton's men" },
                new Character { HouseId = 62, Name = "Mago", Alive = false, EpisodeOfDeath = 8, Gender = "Male", Actor = "Ivailo Dimitrov", CauseOfDeath = "Killed by Khal Drogo" },
                new Character { HouseId = 12, Name = "Marianne Frey", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Katie Creaven", CauseOfDeath = "N/A" },
                new Character { HouseId = 9, Name = "Hoster Tully", Alive = false, EpisodeOfDeath = 22, Gender = "Male", Actor = "Christopher Newman", CauseOfDeath = "Died of old age" },
                new Character { HouseId = 62, Name = "Donnel Hill", Alive = false, EpisodeOfDeath = 39, Gender = "Male", Actor = "Jack Roth", CauseOfDeath = "Killed by Mag Mar Tun Doh Weg" },
                new Character { HouseId = 62, Name = "Quinn", Alive = false, EpisodeOfDeath = null, Gender = "Male", Actor = "Oryan Landa", CauseOfDeath = "Died of injuries from the battle of the Wispering Wood" },
                new Character { HouseId = 21, Name = "Howland Reed", Alive = true, EpisodeOfDeath = null, Gender = "Male", Actor = "Leo Woodruff", CauseOfDeath = "N/A" },
                new Character { HouseId = 62, Name = "Alanna", Alive = true, EpisodeOfDeath = null, Gender = "Female", Actor = "Kim Chapman", CauseOfDeath = "N/A" });
            context.SaveChanges();

            context.Episodes.AddOrUpdate(
                c => c.Title,
                new Episode { Season = 1, EpisodeNumber = 1, Title = "Winter is Coming", RunTime = 62 },
                new Episode { Season = 1, EpisodeNumber = 2, Title = "The Kingsroad", RunTime = 56 },
                new Episode { Season = 1, EpisodeNumber = 3, Title = "Lord Snow", RunTime = 58 },
                new Episode { Season = 1, EpisodeNumber = 4, Title = "Cripples, Bastards, and Broken Things", RunTime = 56 },
                new Episode { Season = 1, EpisodeNumber = 5, Title = "The Wolf and the Lion", RunTime = 55 },
                new Episode { Season = 1, EpisodeNumber = 6, Title = "A Golden Crown", RunTime = 53 },
                new Episode { Season = 1, EpisodeNumber = 7, Title = "You Win or You Die", RunTime = 58 },
                new Episode { Season = 1, EpisodeNumber = 8, Title = "The Pointy End", RunTime = 59 },
                new Episode { Season = 1, EpisodeNumber = 9, Title = "Baelor", RunTime = 57 },
                new Episode { Season = 1, EpisodeNumber = 10, Title = "Fire and Blood", RunTime = 53 },
                new Episode { Season = 2, EpisodeNumber = 1, Title = "The North Remembers", RunTime = 53 },
                new Episode { Season = 2, EpisodeNumber = 2, Title = "The Night Lands", RunTime = 54 },
                new Episode { Season = 2, EpisodeNumber = 3, Title = "What is Dead May Never Die", RunTime = 53 },
                new Episode { Season = 2, EpisodeNumber = 4, Title = "Garden of Bones", RunTime = 51 },
                new Episode { Season = 2, EpisodeNumber = 5, Title = "The Ghost of Harrenhal", RunTime = 55 },
                new Episode { Season = 2, EpisodeNumber = 6, Title = "The Old Gods and the New", RunTime = 54 },
                new Episode { Season = 2, EpisodeNumber = 7, Title = "A Man Without Honor", RunTime = 56 },
                new Episode { Season = 2, EpisodeNumber = 8, Title = "The Prince of Winterfell", RunTime = 54 },
                new Episode { Season = 2, EpisodeNumber = 9, Title = "Blackwater", RunTime = 55 },
                new Episode { Season = 2, EpisodeNumber = 10, Title = "Valar Morghulis", RunTime = 64 },
                new Episode { Season = 3, EpisodeNumber = 1, Title = "Valer Dohaeris", RunTime = 55 },
                new Episode { Season = 3, EpisodeNumber = 2, Title = "Dark WIngs, Dark Words", RunTime = 57 },
                new Episode { Season = 3, EpisodeNumber = 3, Title = "Walk of Punishment", RunTime = 53 },
                new Episode { Season = 3, EpisodeNumber = 4, Title = "And Now His Watch is Ended", RunTime = 54 },
                new Episode { Season = 3, EpisodeNumber = 5, Title = "Kissed by Fire", RunTime = 58 },
                new Episode { Season = 3, EpisodeNumber = 6, Title = "The Climb", RunTime = 53 },
                new Episode { Season = 3, EpisodeNumber = 7, Title = "The Bear and the Maiden Fair", RunTime = 57 },
                new Episode { Season = 3, EpisodeNumber = 8, Title = "Second Sons", RunTime = 56 },
                new Episode { Season = 3, EpisodeNumber = 9, Title = "The Rains of Castamere", RunTime = 52 },
                new Episode { Season = 3, EpisodeNumber = 10, Title = "Mhysa", RunTime = 62 },
                new Episode { Season = 4, EpisodeNumber = 1, Title = "Two Swords", RunTime = 58 },
                new Episode { Season = 4, EpisodeNumber = 2, Title = "The Lion and the Rose", RunTime = 52 },
                new Episode { Season = 4, EpisodeNumber = 3, Title = "Breaker of Chains", RunTime = 57 },
                new Episode { Season = 4, EpisodeNumber = 4, Title = "Oathkeeper", RunTime = 55 },
                new Episode { Season = 4, EpisodeNumber = 5, Title = "First of His Name", RunTime = 53 },
                new Episode { Season = 4, EpisodeNumber = 6, Title = "The Laws of Gods and Men", RunTime = 50 },
                new Episode { Season = 4, EpisodeNumber = 7, Title = "Mockingbird", RunTime = 51 },
                new Episode { Season = 4, EpisodeNumber = 8, Title = "The Mountain and the Viper", RunTime = 52 },
                new Episode { Season = 4, EpisodeNumber = 9, Title = "The Watchers on the Wall", RunTime = 50 },
                new Episode { Season = 4, EpisodeNumber = 10, Title = "The Children", RunTime = 65 },
                new Episode { Season = 5, EpisodeNumber = 1, Title = "The Wars to Come", RunTime = 52 },
                new Episode { Season = 5, EpisodeNumber = 2, Title = "The House of Black and White", RunTime = 55 },
                new Episode { Season = 5, EpisodeNumber = 3, Title = "High Sparrow", RunTime = 60 },
                new Episode { Season = 5, EpisodeNumber = 4, Title = "Sons of the Harpy", RunTime = 50 },
                new Episode { Season = 5, EpisodeNumber = 5, Title = "Kill the Boy", RunTime = 57 },
                new Episode { Season = 5, EpisodeNumber = 6, Title = "Unbowed, Unbent, Unbroken", RunTime = 54 },
                new Episode { Season = 5, EpisodeNumber = 7, Title = "The Gift", RunTime = 59 },
                new Episode { Season = 5, EpisodeNumber = 8, Title = "Hardhome", RunTime = 60 },
                new Episode { Season = 5, EpisodeNumber = 9, Title = "The Dance of Dragons", RunTime = 53 },
                new Episode { Season = 5, EpisodeNumber = 10, Title = "Mother's Mercy", RunTime = 61 },
                new Episode { Season = 6, EpisodeNumber = 1, Title = "The Red Woman", RunTime = 50 },
                new Episode { Season = 6, EpisodeNumber = 2, Title = "Home", RunTime = 54 },
                new Episode { Season = 6, EpisodeNumber = 3, Title = "Oathbreaker", RunTime = 53 },
                new Episode { Season = 6, EpisodeNumber = 4, Title = "Book of the Stranger", RunTime = 59 },
                new Episode { Season = 6, EpisodeNumber = 5, Title = "The Door", RunTime = 57 },
                new Episode { Season = 6, EpisodeNumber = 6, Title = "Blood of My Blood", RunTime = 52 },
                new Episode { Season = 6, EpisodeNumber = 7, Title = "The Broken Man", RunTime = 51 },
                new Episode { Season = 6, EpisodeNumber = 8, Title = "No One", RunTime = 59 },
                new Episode { Season = 6, EpisodeNumber = 9, Title = "Battle of the Bastards", RunTime = 60 },
                new Episode { Season = 6, EpisodeNumber = 10, Title = "The Winds of Winter", RunTime = 68 },
                new Episode { Season = 7, EpisodeNumber = 1, Title = "Dragonstone", RunTime = 59 },
                new Episode { Season = 7, EpisodeNumber = 2, Title = "Stormborn", RunTime = 59 },
                new Episode { Season = 7, EpisodeNumber = 3, Title = "The Queen's Justice", RunTime = 63 },
                new Episode { Season = 7, EpisodeNumber = 4, Title = "The Spoils of War", RunTime = 50 },
                new Episode { Season = 7, EpisodeNumber = 5, Title = "Eastwatch", RunTime = 59 },
                new Episode { Season = 7, EpisodeNumber = 6, Title = "Beyond the Wall", RunTime = 70 },
                new Episode { Season = 7, EpisodeNumber = 7, Title = "The Dragon and the Wolf", RunTime = 80 },
                new Episode { Season = 8, EpisodeNumber = 1, Title = "Winterfell", RunTime = 54 },
                new Episode { Season = 8, EpisodeNumber = 2, Title = "A Knight of the Seven Kingdoms", RunTime = 58 },
                new Episode { Season = 8, EpisodeNumber = 3, Title = "The Long Night", RunTime = 82 },
                new Episode { Season = 8, EpisodeNumber = 4, Title = "The Last of the Starks", RunTime = 78 },
                new Episode { Season = 8, EpisodeNumber = 5, Title = "The Bells", RunTime = 78 },
                new Episode { Season = 8, EpisodeNumber = 6, Title = "The Iron Throne", RunTime = 79 });
            context.SaveChanges();
            context.CharacterEpisodes.AddOrUpdate(
                c => c.Id,
                new CharacterEpisode { Id = 1, CharacterId = 1, EpisodeId = 1 },
                new CharacterEpisode { Id = 2, CharacterId = 1, EpisodeId = 2 });
            context.SaveChanges();
        }
    }
}
